spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/webservice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#콘솔 로그        show_sql:
        format_sql: true


logging.level:
  org.hibernate.sql: debug